spring:
  application:
    name: CART-SERVICES
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  data:
    mongodb:
      authentication-database: admin
      database: cart-services
      host: localhost
      port: 27017
      username: root
      password: password
      auto-index-creation: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 251
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true