spring:
  application:
    name: Book-services
  data:
    mongodb:
      authentication-database: admin
      database: book-services
      port: 27018
      username: root
      password: password
      auto-index-creation: true
      host: localhost
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka