spring:
  application:
    name: Book-services
  data:
    mongodb:
      authentication-database: admin
      database: book-services
      port: 27017
      username: root
      password: password
      auto-index-creation: true
      host: localhost
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8011/realms/owen-book-store
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka